// Shortcut database, keyed by OS family: "mac" or "other" (win/linux/cros).
// Each entry: { category, action, keys }
const SHORTCUT_DATA = {
  mac: [
    { category: "DevTools", action: "Open DevTools", keys: "Cmd+Opt+I" },
    { category: "DevTools", action: "Open DevTools on Elements panel", keys: "Cmd+Shift+C" },
    { category: "DevTools", action: "Open DevTools Console panel", keys: "Cmd+Opt+J" },
    { category: "DevTools", action: "Open Network panel (via DevTools)", keys: "Cmd+Opt+I then click Network" },
    { category: "DevTools", action: "Open Command Menu inside DevTools", keys: "Cmd+Shift+P" },
    { category: "Reload", action: "Hard reload (bypass cache)", keys: "Cmd+Shift+R" },
    { category: "Reload", action: "Normal reload", keys: "Cmd+R" },
    { category: "Tabs", action: "New tab", keys: "Cmd+T" },
    { category: "Tabs", action: "Close tab", keys: "Cmd+W" },
    { category: "Tabs", action: "Reopen last closed tab", keys: "Cmd+Shift+T" },
    { category: "Tabs", action: "Next tab", keys: "Cmd+Opt+Right" },
    { category: "Tabs", action: "Previous tab", keys: "Cmd+Opt+Left" },
    { category: "Tabs", action: "Jump to specific tab (1-8)", keys: "Cmd+1 ... Cmd+8" },
    { category: "Tabs", action: "Jump to last tab", keys: "Cmd+9" },
    { category: "Tabs", action: "Duplicate tab", keys: "Cmd+drag tab, or right-click > Duplicate" },
    { category: "Window", action: "New window", keys: "Cmd+N" },
    { category: "Window", action: "New Incognito window", keys: "Cmd+Shift+N" },
    { category: "Window", action: "Close window", keys: "Cmd+Shift+W" },
    { category: "Window", action: "Minimize window", keys: "Cmd+M" },
    { category: "Navigation", action: "Go back", keys: "Cmd+[  or  Cmd+Left" },
    { category: "Navigation", action: "Go forward", keys: "Cmd+]  or  Cmd+Right" },
    { category: "Navigation", action: "Focus address bar", keys: "Cmd+L" },
    { category: "Navigation", action: "Open Downloads tray/page", keys: "Cmd+Shift+J" },
    { category: "Navigation", action: "Open History page", keys: "Cmd+Y" },
    { category: "Navigation", action: "Open Chrome Task Manager", keys: "Shift+Esc" },
    { category: "Zoom", action: "Zoom in", keys: "Cmd+Plus" },
    { category: "Zoom", action: "Zoom out", keys: "Cmd+Minus" },
    { category: "Zoom", action: "Reset zoom", keys: "Cmd+0" },
    { category: "Bookmarks", action: "Bookmark current page", keys: "Cmd+D" },
    { category: "Bookmarks", action: "Open Bookmark Manager", keys: "Cmd+Opt+B" },
    { category: "Search", action: "Find on page", keys: "Cmd+F" },
    { category: "Search", action: "Search/omnibox from anywhere", keys: "Cmd+L then type" },
    { category: "Misc", action: "Open a new tab and focus it instantly", keys: "Cmd+T" },
    { category: "Misc", action: "View page source", keys: "Cmd+Opt+U" },
    { category: "Misc", action: "Print current page", keys: "Cmd+P" },
    { category: "Misc", action: "Save page as", keys: "Cmd+S" },
    { category: "Misc", action: "Full screen toggle", keys: "Cmd+Ctrl+F" },
    { category: "Tabs", action: "Search open tabs", keys: "Cmd+Shift+A" },
    { category: "Tabs", action: "Bookmark all open tabs at once", keys: "Cmd+Shift+D" },
    { category: "Tabs", action: "Pin/unpin current tab", keys: "Right-click tab > Pin" },
    { category: "Tabs", action: "Mute current tab", keys: "Right-click tab > Mute Site" },
    { category: "Tab Groups", action: "Group current tab", keys: "Right-click tab > Add tab to new group" },
    { category: "Tab Groups", action: "Close all tabs in a group", keys: "Right-click group name > Close group" },
    { category: "Reading List", action: "Open Reading List panel", keys: "Toolbar > Side panel icon (no default key)" },
    { category: "Apps/PWA", action: "Install current site as an app", keys: "Address bar > Install icon (no default key)" },
    { category: "Extensions", action: "Open Extensions management page", keys: "Address bar: chrome://extensions" },
    { category: "Passwords", action: "Open Password Manager", keys: "Address bar: chrome://password-manager" },
    { category: "Capture", action: "Take a screenshot", keys: "Cmd+Shift+5 (macOS system), or right-click > Screenshot" },
    { category: "Privacy", action: "Open Clear Browsing Data dialog", keys: "Cmd+Shift+Delete" },
    { category: "Profiles", action: "Switch/manage Chrome profiles", keys: "Toolbar > Profile avatar icon" },
    { category: "Window", action: "Cycle through open Chrome windows", keys: "Cmd+`" },
    { category: "Navigation", action: "Complete www./.com in address bar", keys: "Ctrl+Return" },
    { category: "Navigation", action: "Show/hide Bookmarks bar", keys: "Cmd+Shift+B" },
    { category: "Misc", action: "Open Settings", keys: "Address bar: chrome://settings" },
    { category: "Misc", action: "Search Chrome's Help menu", keys: "Cmd+Shift+/" }
  ],
  other: [
    { category: "DevTools", action: "Open DevTools", keys: "Ctrl+Shift+I  or  F12" },
    { category: "DevTools", action: "Open DevTools on Elements panel", keys: "Ctrl+Shift+C" },
    { category: "DevTools", action: "Open DevTools Console panel", keys: "Ctrl+Shift+J" },
    { category: "DevTools", action: "Open Network panel (via DevTools)", keys: "F12 then click Network" },
    { category: "DevTools", action: "Open Command Menu inside DevTools", keys: "Ctrl+Shift+P" },
    { category: "Reload", action: "Hard reload (bypass cache)", keys: "Ctrl+Shift+R" },
    { category: "Reload", action: "Normal reload", keys: "Ctrl+R  or  F5" },
    { category: "Tabs", action: "New tab", keys: "Ctrl+T" },
    { category: "Tabs", action: "Close tab", keys: "Ctrl+W" },
    { category: "Tabs", action: "Reopen last closed tab", keys: "Ctrl+Shift+T" },
    { category: "Tabs", action: "Next tab", keys: "Ctrl+Tab" },
    { category: "Tabs", action: "Previous tab", keys: "Ctrl+Shift+Tab" },
    { category: "Tabs", action: "Jump to specific tab (1-8)", keys: "Ctrl+1 ... Ctrl+8" },
    { category: "Tabs", action: "Jump to last tab", keys: "Ctrl+9" },
    { category: "Tabs", action: "Duplicate tab", keys: "Ctrl+drag tab, or right-click > Duplicate" },
    { category: "Window", action: "New window", keys: "Ctrl+N" },
    { category: "Window", action: "New Incognito window", keys: "Ctrl+Shift+N" },
    { category: "Window", action: "Close window", keys: "Ctrl+Shift+W" },
    { category: "Window", action: "Minimize window", keys: "Win+Down or Alt+Space" },
    { category: "Navigation", action: "Go back", keys: "Alt+Left" },
    { category: "Navigation", action: "Go forward", keys: "Alt+Right" },
    { category: "Navigation", action: "Focus address bar", keys: "Ctrl+L  or  Alt+D" },
    { category: "Navigation", action: "Open Downloads tray/page", keys: "Ctrl+J" },
    { category: "Navigation", action: "Open History page", keys: "Ctrl+H" },
    { category: "Navigation", action: "Open Chrome Task Manager", keys: "Shift+Esc" },
    { category: "Zoom", action: "Zoom in", keys: "Ctrl+Plus" },
    { category: "Zoom", action: "Zoom out", keys: "Ctrl+Minus" },
    { category: "Zoom", action: "Reset zoom", keys: "Ctrl+0" },
    { category: "Bookmarks", action: "Bookmark current page", keys: "Ctrl+D" },
    { category: "Bookmarks", action: "Open Bookmark Manager", keys: "Ctrl+Shift+O" },
    { category: "Search", action: "Find on page", keys: "Ctrl+F" },
    { category: "Search", action: "Search/omnibox from anywhere", keys: "Ctrl+L then type" },
    { category: "Misc", action: "View page source", keys: "Ctrl+U" },
    { category: "Misc", action: "Print current page", keys: "Ctrl+P" },
    { category: "Misc", action: "Save page as", keys: "Ctrl+S" },
    { category: "Misc", action: "Full screen toggle", keys: "F11" },
    { category: "Tabs", action: "Search open tabs", keys: "Ctrl+Shift+A" },
    { category: "Tabs", action: "Bookmark all open tabs at once", keys: "Ctrl+Shift+D" },
    { category: "Tabs", action: "Pin/unpin current tab", keys: "Right-click tab > Pin" },
    { category: "Tabs", action: "Mute current tab", keys: "Right-click tab > Mute Site" },
    { category: "Tab Groups", action: "Group current tab", keys: "Right-click tab > Add tab to new group" },
    { category: "Tab Groups", action: "Close all tabs in a group", keys: "Right-click group name > Close group" },
    { category: "Reading List", action: "Open Reading List panel", keys: "Toolbar > Side panel icon (no default key)" },
    { category: "Apps/PWA", action: "Install current site as an app", keys: "Address bar > Install icon (no default key)" },
    { category: "Extensions", action: "Open Extensions management page", keys: "Address bar: chrome://extensions" },
    { category: "Passwords", action: "Open Password Manager", keys: "Address bar: chrome://password-manager" },
    { category: "Capture", action: "Take a screenshot", keys: "Win+Shift+S (Windows system), or right-click > Screenshot" },
    { category: "Privacy", action: "Open Clear Browsing Data dialog", keys: "Ctrl+Shift+Delete" },
    { category: "Profiles", action: "Switch/manage Chrome profiles", keys: "Toolbar > Profile avatar icon" },
    { category: "Window", action: "Cycle through open windows", keys: "Alt+Tab (system-level)" },
    { category: "Navigation", action: "Complete www./.com in address bar", keys: "Ctrl+Enter" },
    { category: "Navigation", action: "Show/hide Bookmarks bar", keys: "Ctrl+Shift+B" },
    { category: "Misc", action: "Open Settings", keys: "Address bar: chrome://settings" },
    { category: "Misc", action: "Search Chrome's Help menu", keys: "Alt+Shift+H" }
  ]
};
